
samples: /gpfs/project/projects/medbioinf/projects/mihen108/strand-seq-graph-phasing/config/samples_hgsvc-renewal.tsv
# modify this to be some sort of num alignments?
segmentLengthThreshold: 250000

# currently only applies to the R environment rules
deploy_offline: True
singularity_Renv: /gpfs/project/projects/medbioinf/projects/mihen108/env_Renv2.sif

# scripts
scripts_dir: /gpfs/project/projects/medbioinf/projects/mihen108/strand-seq-graph-phasing/scripts/

# evaluation
## reference fasta
reference: /gpfs/project/projects/medbioinf/projects/mihen108/input/references/T2Tv11_hg002Yv2_chm13.fasta